# Generated by Django 4.2.1 on 2023-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store_cusmt_last_na_b92e19_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_cusmtomers',
        ),
    ]
